updates
merged:

  flora: 00d3940c79b13cbc2ff4185aa82a4ee47f4a3ff8
  faustoo: 87d63ffce41c5ef1abeddc2f4711a0aad3b539d4
  fusion809: 825b48c351858bddcfa391c4b0a97e74cadeec9f
  deadbeef: 53e0a41db6e7193bd83ef117f8055457f0990cb7
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 82fec763e4e78b845e30e0344420aab768b020d2

diff --git a/dev-python/templates/docutils.tmpl b/dev-python/templates/docutils.tmpl
--- a/dev-python/templates/docutils.tmpl
+++ b/dev-python/templates/docutils.tmpl
@@ -1,22 +1,23 @@
-# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
 
-PYTHON_COMPAT=( python2_7 python3_{5,6,7} pypy pypy3 )
+PYTHON_COMPAT=( {{python_compat}} )
 
 inherit distutils-r1
 
 DESCRIPTION="Python Documentation Utilities"
 HOMEPAGE="http://docutils.sourceforge.net/ https://pypi.org/project/docutils/"
-SRC_URI="mirror://sourceforge/${PN}/${P}.tar.gz"
+#SRC_URI="mirror://sourceforge/${PN}/${P}.tar.gz"
+SRC_URI="{{artifacts[0].src_uri}}"
 
 LICENSE="BSD-2 GPL-3 public-domain"
 SLOT="0"
-KEYWORDS="alpha amd64 arm arm64 hppa ia64 ~m68k ~mips ppc ppc64 ~riscv ~s390 ~sh sparc x86 ~ppc-aix ~x64-cygwin ~amd64-fbsd ~x86-fbsd ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~m68k-mint ~sparc-solaris ~sparc64-solaris ~x64-solaris ~x86-solaris"
+KEYWORDS="*"
 IUSE=""
 
-DEPEND="dev-python/pygments[${PYTHON_USEDEP}]"
+BDEPEND="dev-python/setuptools[${PYTHON_USEDEP}]
+	dev-python/pygments[${PYTHON_USEDEP}]"
 RDEPEND="${DEPEND}"
 
 python_compile_all() {
@@ -30,14 +31,13 @@ python_compile_all() {
 		--stylesheet-path=../html4css1.css, --traceback ../docs || die
 }
 
+src_test() {
+	cd test || die
+	distutils-r1_src_test
+}
+
 python_test() {
-	if python_is_python3; then
-		pushd test3 > /dev/null || die
-	else
-		pushd test > /dev/null || die
-	fi
-	"${EPYTHON}" alltests.py || die "Testing failed with ${EPYTHON}"
-	popd > /dev/null || die
+	"${EPYTHON}" alltests.py -v || die "Testing failed with ${EPYTHON}"
 }
 
 python_install() {
